sudo: required

language: python
python:
  - '3.5'

env:
  - NODE_VERSION='8.11.3'

addons:
  apt:
    update: true
    packages:
      - python3-pip

before_install:
  - nvm install $NODE_VERSION

install:
  - gem install --no-ri --no-rdoc fpm
  - yarn install

script:
  - yarn build
  - sh scripts/make_deb.sh

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: '*.deb'
  file_glob: true
  skip_cleanup: true
  name: $TRAVIS_TAG
  on:
    branch: master
    tags: true